### ISSUE TITLE
No function names on plot

### ISSUE THREAD

**Issue by neighthan** [kimikage/ProfileSVG.jl#4] opened 2020-04-12 03:59 UTC
I tried to run the example from the README (code below), and I get almost the same plot, except there are no function names written on it. Does this need to be enabled somehow or is this a bug? (nothing appears on hovering over the plot either)

![image](https://user-images.githubusercontent.com/12573501/79060198-23ea3180-7c50-11ea-87d5-40d32a2e70d0.png)

```julia
using Profile
using ProfileSVG

function profile_test(n)
    for i = 1:n
        A = randn(100,100,20)
        m = maximum(A)
        Am = mapslices(sum, A; dims=2)
        B = A[:,:,5]
        Bsort = mapslices(sort, B; dims=1)
        b = rand(100)
        C = B.*b
    end
end

profile_test(1)   # run once to compile

Profile.clear()
@profview profile_test(10)
```

Versions
* Julia: 1.4.0
* ProfileSVG: 0.1.0
* IJulia: 1.21.1

**Comment by timholy** [comment] 2020-04-12 14:15
I think I've seen that too but I think it depends on how you're visualizing the SVG file? It's been a long time and I can't remember. You might want to inspect the produced SVG file to check whether the names are there somewhere.

I generally recommend `ProfileVega.jl` or `ProfileView.jl` over this package. They all use `FlameGraphs.jl` as the core, but the SVG output has not been maintained and needs someone to help (as indicated in the README).

**Comment by kimikage** [comment] 2020-04-29 00:27
I can't reproduce this issue (on Chrome and Firefox on Windows 10).

**Edit:**
I had the same issue when I replaced the bundled Snap.svg with the final official release v0.5.1. 
However, in my case, the saved standalone SVG files are fine. So it seems to be a compatibility issue with Jupyter.

**Comment by kimikage** [comment] 2020-04-30 07:19
I think this is a dependency problem with the AMD (Asynchronous Module Definition). If Snap.svg is already loaded on Jupyter, ProfileSVG will use it. This problem happens if other packages or plugins used Snap.svg.

**Comment by kimikage** [comment] 2020-04-30 13:18
I think it's worth checking out PR #12. However, the URL in the General registry has not been updated yet, so you need to set the new URL manually.

**Edit:**
ProfileSVG v0.1.1 was released.
@neighthan, if it's not too much trouble, please let me know the result.
FYI, v0.1.2 will be released soon.
**Edit2:**
v0.1.3 was released.

**Comment by kimikage** [comment] 2020-06-05 14:17
If the problem has not been fixed, please reopen this.

**Closed as completed by kimikage** 2020-06-05 14:17 UTC
